services:
  # Supabase RAG Service
  - type: web
    name: simple-rag-supabase
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run simpleRAG.py --server.port $PORT --server.address 0.0.0.0 --server.headless true
    envVars:
      - key: SUPABASE_URL
        sync: false  # Set in Render dashboard
      - key: SUPABASE_KEY
        sync: false  # Set in Render dashboard
      - key: OPENAI_API_KEY
        sync: false  # Set in Render dashboard
      - key: PYTHONUNBUFFERED
        value: "1"
  
  # Pinecone RAG Service (uncomment to deploy)
  # - type: web
  #   name: simple-rag-pinecone
  #   runtime: python3
  #   buildCommand: pip install -r requirements_pinecone.txt
  #   startCommand: streamlit run pinecone_rag.py --server.port $PORT --server.address 0.0.0.0 --server.headless true
  #   envVars:
  #     - key: PINECONE_API_KEY
  #       sync: false  # Set in Render dashboard
  #     - key: PINECONE_INDEX_NAME
  #       sync: false  # Set in Render dashboard
  #     - key: OPENAI_API_KEY
  #       sync: false  # Set in Render dashboard
  #     - key: PYTHONUNBUFFERED
  #       value: "1" 